# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run  
on:
  push:  
    branches: [ "main" ]       
  pull_request: 
    branches: [ "main" ]    
  workflow_dispatch: 

jobs:
  LLVM_build:
    strategy:
      matrix:
        arch: [arm64, x86]
    runs-on: ${{ matrix.arch == 'x86' && 'arc-runner-set-x86' || 'arc-runner-set-ampere' }}

    steps:
      - name: Log Operating System Details
        run: |
          echo "Architecture: ${{ matrix.arch }}"
          uname -a
          lsb_release -a || cat /etc/os-release
          lscpu
      
      # - name: Checkout LLVM source code
      #   uses: actions/checkout@v4
      #   with:
      #     repository: llvm/llvm-project
      #     path: llvm-project

      # - name: Set up build environment
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y build-essential cmake ninja-build python3

      # - name: Configure LLVM build
      #   run: |
      #     mkdir -p llvm-project/build
      #     cd llvm-project/build
      #     cmake -G Ninja \
      #       -DLLVM_ENABLE_PROJECTS="clang" \
      #        -DLLVM_ENABLE_RUNTIMES="libunwind;libcxx;libcxxabi" \
      #       -DLLVM_TARGETS_TO_BUILD="AArch64;X86" \
      #       -DCMAKE_BUILD_TYPE=Release \
      #       -DLLVM_ENABLE_ASSERTIONS=ON \
      #       ../llvm

      # - name: Build LLVM
      #   run: |
      #     cd llvm-project/build
      #     ninja
      #   env:
      #     LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}

      # - name: Display build information
      #   run: |
      #     echo "Architecture: ${{ matrix.arch }}"
      #     echo "Build completed on $(date)"

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: llvm-build-${{ matrix.arch }}
      #     path: llvm-project/build

  deploy:
    needs: LLVM_build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ubuntu-latest

    steps:
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: llvm-build-${{ matrix.arch }}
      #     path: llvm-build-${{ matrix.arch }}

      - name: List root directory contents
        run: |
          ls -la
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository contents
        run: |
          ls -la $GITHUB_WORKSPACE
          pwd
      

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Verify Docker Login
        run: docker info

      - name: List root directory contents
        run: |
          ls -la

      - name: List repo
        run: |
          ls $GITHUB_WORKSPACE
          pwd 
          
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-project:${{ matrix.arch }}-latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-project:${{ matrix.arch }}-latest

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Sync Argo CD Application
        env:
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
        run: |
          argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
          argocd app sync nginx-app
